# Generated by Django 4.0.3 on 2022-03-30 22:39

from django.db import migrations


def create_trial_plan(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SaasPlan = apps.get_model("subscriptions", "SaasPlan")
    SaasPlan.objects.using(db_alias).create(
        name="TRIAL", display_name="Trial", stripe_product_id="trial"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_trial_plan),
    ]
